[package]
name = "examples"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
publish = false

[[bin]]
name = "basic_world"
path = "basic_world.rs"

[dependencies]
stratum = { workspace = true }
stratum-helio = { workspace = true }
helio = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
